import Head from "next/head";
import { ConnectButton } from "@web3uikit/web3";
import React from "react";

export const RootLayout: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  return (
    <>
      <Head>
        <title>Hime Avatar ❀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-8">
        <header className="flex flex-col md:flex-row justify-center items-center gap-2">
          <h1 className="text-4xl font-bold">Hime Avatar ❀</h1>
          <ConnectButton />
        </header>
        <hr className="m-8" />
        <main>{children}</main>
      </div>
    </>
  );
};
