import Head from "next/head";
import React from "react";
import { Divider } from "antd";
import { ConnectButton } from "@/components";

export const RootLayout: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  return (
    <>
      <Head>
        <title>Hime Avatar ❀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-8">
        <header className="flex flex-col md:flex-row justify-center items-center md:gap-2">
          <h1
            className="text-4xl font-bold"
            style={{
              backgroundImage:
                "linear-gradient(90deg, #ffafbd 0%, #17b4ff 100%)",
              WebkitBackgroundClip: "text",
              color: "transparent",
            }}
          >
            Hime Avatar ❀
          </h1>
          <ConnectButton />
        </header>
        <Divider />
        <main>{children}</main>
      </div>
    </>
  );
};
